import React, { useState, useEffect, useRef } from 'react';
import { 
  LayoutDashboard, Package, FileText, Settings, Users,
  Plus, Edit, Trash2, AlertTriangle, Download,
  RotateCcw, ArrowUpDown, X, Printer, Moon, Sun, FilterX, UploadCloud, DownloadCloud, Database
} from 'lucide-react';
import { 
  PieChart, Pie, Cell, Tooltip as RechartsTooltip, Legend, ResponsiveContainer,
  BarChart, Bar, XAxis, YAxis, CartesianGrid
} from 'recharts';
import { DEFAULT_CATEGORIES, DUMMY_DATA, DUMMY_SUPPLIERS, getTheme } from '../utils/constants';

const SettingsTab = ({ 
  isDarkMode, setIsDarkMode, 
  inventory = [], setInventory, 
  suppliers = [], setSuppliers, 
  invoices = [], setInvoices, 
  categories = [], setCategories,
  sales = [], setSales,               
  customers = [], setCustomers,       
  discountRules = [], setDiscountRules, // <-- ADDED RULES
  theme 
}) => {
  const fileInputRef = useRef(null);

  const handleBackup = () => {
    // Gather ALL Data
    const systemState = {
      inventory,
      suppliers,
      invoices,
      categories,
      sales,
      customers,
      discountRules
    };

    const dataStr = JSON.stringify(systemState, null, 2);
    const blob = new Blob([dataStr], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    
    const link = document.createElement("a");
    link.href = url;
    link.download = `smart_inventory_backup_${new Date().toISOString().split('T')[0]}.json`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleRestore = (e) => {
    const file = e.target.files[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (event) => {
      try {
        const parsedData = JSON.parse(event.target.result);
        
        if (window.confirm("⚠️ WARNING: Restoring a backup will overwrite ALL your current data. Are you sure you want to proceed?")) {
          if (parsedData.inventory && setInventory) setInventory(parsedData.inventory);
          if (parsedData.suppliers && setSuppliers) setSuppliers(parsedData.suppliers);
          if (parsedData.invoices && setInvoices) setInvoices(parsedData.invoices);
          if (parsedData.categories && setCategories) setCategories(parsedData.categories);
          if (parsedData.sales && setSales) setSales(parsedData.sales);
          if (parsedData.customers && setCustomers) setCustomers(parsedData.customers);
          if (parsedData.discountRules && setDiscountRules) setDiscountRules(parsedData.discountRules);
          
          alert("✅ Backup restored successfully! Your system is now up to date.");
        }
      } catch (error) {
        alert("❌ Error reading backup file. Please ensure it is a valid JSON backup generated by this system.");
        console.error(error);
      }
      e.target.value = '';
    };
    
    reader.readAsText(file);
  };

  return (
    <div className="max-w-3xl mx-auto animate-in fade-in duration-500 no-print">
      <h2 className={`text-2xl font-bold ${theme.textMain} mb-6`}>System Settings</h2>
      
      <div className={`${theme.bgCard} rounded-xl shadow-sm border ${theme.border} overflow-hidden`}>
        
        <div className="p-6">
          <h3 className={`text-lg font-semibold ${theme.textMain} mb-4 flex items-center gap-2`}>
            {isDarkMode ? <Moon className="w-5 h-5 text-indigo-500"/> : <Sun className="w-5 h-5 text-yellow-500"/>}
            Appearance
          </h3>
          <button onClick={() => setIsDarkMode(!isDarkMode)} className={`flex items-center gap-3 px-6 py-3 rounded-lg border ${theme.border} ${theme.hover} ${theme.textMain} transition-all font-medium`}>
             {isDarkMode ? 'Switch to Light Mode' : 'Switch to Dark Mode'}
          </button>
        </div>

        <div className={`p-6 border-t ${theme.border}`}>
          <h3 className={`text-lg font-semibold ${theme.textMain} mb-4 flex items-center gap-2`}>
            <Database className="w-5 h-5 text-blue-500"/>
            Backup & Restore
          </h3>
          <p className={`text-sm ${theme.textMuted} mb-6`}>
            Download a copy of your entire system (Inventory, Sales, Customers, Discount Rules, etc.) or restore from a previous backup file.
          </p>

          <div className="flex flex-wrap gap-4">
            <button 
              onClick={handleBackup} 
              className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white px-6 py-3 rounded-lg font-medium transition-colors shadow-sm"
            >
              <DownloadCloud className="w-5 h-5" /> Download Backup (JSON)
            </button>

            <input type="file" accept=".json" ref={fileInputRef} onChange={handleRestore} className="hidden" />
            
            <button 
              onClick={() => fileInputRef.current.click()} 
              className={`flex items-center gap-2 px-6 py-3 rounded-lg border ${theme.border} ${theme.textMain} ${theme.hover} font-medium transition-colors`}
            >
              <UploadCloud className="w-5 h-5" /> Restore from Backup
            </button>
          </div>
        </div>

        <div className="p-6 border-t border-red-100 dark:border-red-900/30 bg-red-50/50 dark:bg-red-900/10">
          <h3 className="text-lg font-semibold text-red-600 dark:text-red-400 mb-2 flex items-center gap-2">
            <AlertTriangle className="w-5 h-5"/>
            Danger Zone
          </h3>
          <p className="text-sm text-red-500/80 dark:text-red-400/80 mb-4">
            Resetting the system will permanently delete your current state and load dummy testing data.
          </p>
          <button 
            onClick={() => { 
              if (window.confirm('Wipe all data and load dummy test data?')) { 
                setInventory(DUMMY_DATA); setSuppliers(DUMMY_SUPPLIERS); setInvoices([]); setCategories(DEFAULT_CATEGORIES); 
                if(setSales) setSales([]); if(setCustomers) setCustomers([]); if(setDiscountRules) setDiscountRules([]);
              } 
            }} 
            className="flex items-center gap-2 bg-white dark:bg-gray-800 border border-red-200 dark:border-red-800 text-red-600 dark:text-red-400 px-4 py-2 rounded-lg hover:bg-red-50 dark:hover:bg-red-900/50 shadow-sm transition-colors"
          >
            <RotateCcw className="w-4 h-4" /> Restore Default Test Data
          </button>
        </div>

      </div>
    </div>
  );
};

export default SettingsTab;